In [14]:
import numpy as np
import sys
import time

In [18]:
size = 100000
List_1 = range(size)
List_2 = range(size)
print("Element in list :",List_1)
print("Size of 1 int",sys.getsizeof(1))
print("Toal no of items :",len(List_1))
print("Size of List:",sys.getsizeof(1)*len(List_1))

Element in list : range(0, 100000)
Size of 1 int 28
Toal no of items : 100000
Size of List: 2800000


In [19]:
Array_1 = np.arange(size)
Array_2 = np.arange(size)
print("Array_1.size:",Array_1.dtype)
print("Array_1.itemsize:",Array_1.itemsize)
print("Size of array:",Array_1.size * Array_1.itemsize)

Array_1.size: int32
Array_1.itemsize: 4
Size of array: 400000


In [20]:
List_3 = []
start_time = time.time()
for x in range(0,len(List_1)):
    List_3.append(List_1[x]+List_2[x])
end_time = time.time()
time_of_list = ((end_time - start_time)*1000)
print("Time consume",time_of_list)

Time consume 114.9284839630127


In [13]:
start_time = time.time()
Array_3 = Array_1 + Array_2
end_time = time.time()
print("Time taken",((end_time - start_time)*1000))
print(List_3)
print(Array_3)

Time taken 0.0
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182, 184, 186, 188, 190, 192, 194, 196, 198]
[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100 102 104 106
 108 110 112 114 116 118 120 122 124 126 128 130 132 134 136 138 140 142
 144 146 148 150 152 154 156 158 160 162 164 166 168 170 172 174 176 178
 180 182 184 186 188 190 192 194 196 198]


In [21]:
mylist = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
print(type(mylist))
print(mylist)

<class 'list'>
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]


In [22]:
mynparray = np.array(mylist)
print(type(mynparray))
print(mynparray)

<class 'numpy.ndarray'>
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [23]:
print(mynparray.ndim)

1


In [24]:
print(mynparray.itemsize)

4


In [26]:
tdarray = np.array([[1,2,3],[2,3,4]])
print(tdarray)

[[1 2 3]
 [2 3 4]]


In [27]:
print(tdarray.shape)

(2, 3)


In [28]:
reshaped = tdarray.reshape(3,2)
print(reshaped)

[[1 2]
 [3 2]
 [3 4]]


In [30]:
mz_array = np.zeros((3,2))
print(mz_array.dtype)
print(mz_array)

float64
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [34]:
mz_array = np.ones((3,2),dtype=np.int64)
print(mz_array.dtype)
print(mz_array)

int64
[[1 1]
 [1 1]
 [1 1]]


In [35]:
my_range_array = np.arange(1,24,2)
print(my_range_array)

[ 1  3  5  7  9 11 13 15 17 19 21 23]


In [36]:
my_reshaped_array = my_range_array.reshape(4,3)
print(my_reshaped_array)

[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]
 [19 21 23]]


In [39]:
Array_mult = []
Array_mult = Array_1 * Array_2
print(Array_mult)

[         0          1          4 ... 1409465417 1409665412 1409865409]


In [40]:
Array_1 = np.array([1,2,3,4])
Array_2 = np.array([5,6,7,8])

Array_mult = Array_1 @ Array_2
print(Array_mult)

70


In [41]:
Array_mult = Array_1.dot(Array_2)
print(Array_mult)

70


In [44]:
z=0
for i,j in zip(Array_1,Array_2):
    z = z + i*j
    print(z)

5
17
38
70


In [46]:
Array_7 = np.random.random((5))
print(Array_7 *10)

[7.91243927 1.94950929 3.69787458 5.95109116 6.75177041]


In [51]:
def myfunc(x,y):
    z = x+y
    return z
Array_8 = np.fromfunction(myfunc,(2,3))
print(Array_8)


[[0. 1. 2.]
 [1. 2. 3.]]
